<!DOCTYPE html>
<html>
 
<head>
    <style>
    table,
    th,
    td {
        border: 1px solid black;
    }
    </style>
</head>
 
<body>
    <table style="width:100%">
        <tr>
            <th>Firstname</th>
            <th>Lastname</th>
            <th>location</th>
            <th>price</th>
            <th>startdate</th>
            <th>enddate</th>
            <th>vehicle</th>
        </tr>
        <tr>
            <td>Priya</td>
            <td>Sharma</td>
            <td>warangal</td>
            <td>1500</td>
            <td>20-12-2022</td>
            <td>20-02-2023</td>
            <td>harvestor</td>
        </tr>
        <tr>
            <td>Arun</td>
            <td>Singh</td>
            <td>nizambad</td>
            <td>2500</td>
            <td>15-12-2022</td>
            <td>20-05-2023</td>
            <td>tractor</td>
        </tr>
        <tr>
            <td>Sam</td>
            <td>Watson</td>
            <td>warangal</td>
            <td>500</td>
            <td>20-1-2023</td>
            <td>06-05-2023</td>
            <td>harvestor</td>
        </tr>
        <tr>
            <td>ram</td>
            <td>reddy</td>
            <td>khamma0</td>
            <td>2500</td>
            <td>13-11-2022</td>
            <td>29-05-2023</td>
            <td>harvestor</td>
        </tr>
        <tr>
            <td>ravi</td>
            <td>chandu</td>
            <td>nalgonda</td>
            <td>500</td>
            <td>05-11-2022</td>
            <td>20-02-2023</td>
            <td>tractor</td>
        </tr>
        <tr>
            <td>charan</td>
            <td>Singh</td>
            <td>adilabad</td>
            <td>2500</td>
            <td>15-12-2022</td>
            <td>21-05-2023</td>
            <td>tractor</td>
        </tr>
    </table>
</body>
 
</html>